name: Pages Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check index.html exists
        run: |
          test -f index.html || (echo "::error ::index.html não existe na raiz do repositório" && exit 1)
      - name: List files
        run: ls -la
